name = "sansotec-api"
main = "src/index.ts"
compatibility_date = "2024-11-29"

[[d1_databases]]
binding = "DB"
database_name = "sansotec-db"
database_id = "1545d708-ff1c-4719-9018-26e6c3a0cb76"

[[r2_buckets]]
binding = "R2"                # ეს სახელი გამოვიყენებთ კოდში: c.env.R2
bucket_name = "sansotecfiles"

